apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeting-app
  template:
    metadata:
      labels:
        app: greeting-app
    spec:
      containers:
      - name: greeting-app
        image: docker.io/rlateu/greeting-app:14
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: greeting-config
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 3