name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: rlateu/my-greeting-app
      IMAGE_TAG: ${{ github.run_number }}

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Install dependencies
      - name: Install dependencies
        working-directory: src
        run: npm install

      # Run tests
      - name: Run tests
        working-directory: src
        run: npm test

      # Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      # Build Docker image
      - name: Build Docker image
        working-directory: src
        run: docker build -t $IMAGE_NAME:$IMAGE_TAG .

      # Push Docker image
      - name: Push Docker image
        run: docker push $IMAGE_NAME:$IMAGE_TAG
